name: Push JSON Files

on:
  workflow_dispatch:

jobs:
  push_json:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Run Script to Generate JSON Files
      run: node lb.js

    - name: Commit and Push JSON Files
      run: |
        git config --local user.email "life23243@tutanota.com"
        git config --local user.name "x1yl"
        git add .
        git commit -m "Add JSON files"
        git push
